version: "2"

services:

  gateway:
    build: ./gateway
    ports:
      - "7000:80"
    networks:
      - frontend    
    depends_on:
      - "controller"
      - "mysql-db"

  controller:
    build: ./controller
    ports:
      - 7001:80
      - 7002:443
    environment:
     - PATH=$PATH:/
    networks:
      - frontend
      - backend
    volumes:
      - $PWD/controller/api:/home/www-data/web2py/applications/api:rw
      - /var/run/docker.sock:/docker.sock
    links:
      - mysql-db
    depends_on:
      - "mysql-db"    

  mysql-db:
    build: ./mysqldb
    ports:
      - "3306:3306"
    volumes:
      - /home/adityagaykar/Dev/serverless-platform-db-data:/var/lib/mysql:rw
    networks:
      - backend

networks:
  frontend:
  backend:
