version: "3"

services:
  classifier:
    image: serverlessplatform_classifier
    ports:
      - "8000:8000"
      - "8001:443"
    networks:
      - frontend  
      - backend  
    depends_on:
      - frontend
      - backend
      - "gateway"
      - "controller"
      - "mysql-db"
    deploy:
      replicas: 2


  gateway:
    image: serverlessplatform_gateway
    ports:
      - "7000:80"
    networks:
      - frontend    
    depends_on:
      - frontend
      - backend
      - "controller"
      - "mysql-db"
    deploy:
      replicas: 2

  controller:
    image: serverlessplatform_controller
    ports:
      - 7001:80
      - 7002:443
    networks:
      - frontend
      - backend
    volumes:
      - $PWD/controller/api:/home/www-data/web2py/applications/api:rw
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - mysql-db
    depends_on:
      - frontend
      - backend
      - "mysql-db"
    deploy:
      replicas: 3

  mysql-db:
    image: "serverlessplatform_mysql-db"
    ports:
      - "3306:3306"
    volumes:
      - /home/adityagaykar/dev/serverless-platform-db-data:/var/lib/mysql
    networks:
      - backend
    depends_on:
      - frontend
      - backend
    deploy:
      placement:
        constraints: [node.role == manager]

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    depends_on:
      - gateway
      - controller
      - mysql-db
      - frontend
      - backend
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  frontend:
  backend:
 
