version: 3

services:
 gateway:
    build: ./gateway
    ports:
      - "7000:80"
    networks:
      - frontend    
    depends_on:
      - "controller"
      - "mysql-db"
    deploy:
      placement:
        constraints: [node.role == manager]

  controller:
    build: ./controller
    ports:
      - 7001:80
      - 7002:443
    networks:
      - frontend
      - backend
    volumes:
      - $PWD/controller/api:/home/www-data/web2py/applications/api:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    links:
      - mysql-db
    depends_on:
      - "mysql-db"    
    deploy:
      placement:
        constraints: [node.role == manager]

  mysql-db:
    build: ./mysqldb
    ports:
      - "3306:3306"
    volumes:
      - /home/adityagaykar/dev/serverless-platform-db-data:/var/lib/mysql
    networks:
      - backend
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  frontend:
  backend:
 